<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 24.10.2018
 * Time: 12:52.
 */

namespace DFSClient\Exceptions;

class MainException extends \Exception
{
    public function __toString()
    {
        //parent::__toString(); // TODO: Change the autogenerated stub

        $arr['error']['message'] = $this->message;
        $arr['error']['Code'] = $this->code;
        $arr['error']['file'] = $this->file;
        $arr['error']['line'] = $this->line;
        $arr['error']['prev'] = $this->getPrevious();
        $arr['error']['trace'] = $this->getTrace();

        dump($arr);

        return parent::__toString();
    }
}
